src/objects/LP_Address__c.object
<CustomObject>
    <fields>
        <fullName>LP_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LP_State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LP_Street_Address__c</fullName>
        <inlineHelpText>• Abbreviate the words in the address that indicate direction – North 5th would be N 5th
• 100 Southeast 200 Northwest would be 100 SE 200 NW
• Abbreviate street types (St, Ave, Blvd) – Do not include period
• No periods after abbreviation of name</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LP_Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Street Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LP_AddressController.cls
public class LP_AddressController {

    public LP_AddressController() {
        objAddress = new LP_Address__c();
        objAddress.LP_Street_Address__c = ' ';
        objAddress.LP_City__c = ' ';
        objAddress.LP_State_Province__c = ' ';
        objAddress.LP_Zip_Postal_Code__c = ' ';


    }


    public LP_AddressController(ApexPages.StandardController controller) {
        objAddress = new LP_Address__c();
    }



    PageReference page;
    public LP_Address__c objAddress { get; Set; }


    public PageReference save() {
        if (objAddress.LP_Street_Address__c != null)
        objAddress.name = objAddress.LP_Street_Address__c;
        if (objAddress.LP_City__c != null)
        objAddress.name += objAddress.LP_City__c;
        if (objAddress.LP_State_Province__c != null)
        objAddress.name += objAddress.LP_State_Province__c;
        if (objAddress.LP_Zip_Postal_Code__c != null)
        objAddress.name += objAddress.LP_Zip_Postal_Code__c;

        insert objAddress;
        page = new PageReference('/' + objAddress.id);
        Page.setRedirect(true);
        return page;

    }
}