src/objects/Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Resource__c</fullName>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testSkill.cls
@isTest
public class testSkill{
    
    static testMethod void testBillingAccount(){
        Resource__c objR=new Resource__c(name='test');
        insert objR;
        
        Skill__c obj =new Skill__c ();
        obj.name='Test0';
        obj.Resource__c =objR.Id;
        //insert obj;
        
        Skill__c obj2 =new Skill__c ();
        obj2.name='Test02';
        obj2.Resource__c =objR.Id;
        //insert obj2;
        
        list<Skill__c > objList= new list<Skill__c >{obj,obj2};
        insert objList;
    }


}