src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SkillController.cls
public class SkillController {
 public String inputName {get; set;}
 public String SelectedResourceId{get; set;}
 public list<Resource__c> lstResource {get; set;}
    public list<Skill__c> lstSkills {get; set;}
    public void searchResouceSkills()
    {
     if(inputName != null && inputName !='')
     {
      lstResource = [Select Id from Resource__c where First_Name__c = :inputName limit 1];
      system.debug('List Of resources'+lstResource);
      if(lstResource.size()>0)
      {
         lstSkills = [select Type__c, Resource__c, Rating__c, Name, Id From Skill__c where Resource__c= : SelectedResourceId];
     }
     else
     {
     system.debug('Apex Error');
     }
     }
     else
     {
      system.debug('please fill valid first name of the record');
     }

    }
    
}