src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SkillMatrixDynamicController3.cls
public with sharing class SkillMatrixDynamicController3 {


    public list<Resource__c> lstResource {get; private set;}
    public String SelectedResource {get; set;} 
    public list<Skill__c> lstSkills {get; set;}   
    public integer size {get; set;}
    public String newRating{get; set;}


    
    public list<selectOption> getResourceList() {
         lstResource = [select id , First_Name__c, Last_Name__c from resource__c limit 10];
         List<SelectOption> options = new List<SelectOption>();
         options.add(new Selectoption('', '-Select-'));
         for(Resource__c objResource: lstResource)
         {
             options.add(new SelectOption(objResource.Id,objResource.First_name__c+' ' +objResource.Last_Name__c));
         }
         return Options;
    }
    
    
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public void Save()
    {
        list<Skill__c> lstUpdateSkills = new list<Skill__c>();
        for(Skill__c objSK: lstSkills)
        {
             lstUpdateSkills.add(objSK);   
        }
        update lstUpdateSkills;
    }
    public void searchResourceSkills()
    {
        if(SelectedResource != null && SelectedResource != '')
        {
                lstSkills = [Select notes__c, Type__c, Resource__c, Rating__c, Name, Id From Skill__c where Resource__c =: SelectedResource];
                if(lstSkills.size() > 0)
                {
                    size = lstSkills.size();
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Info, 'Successful'));
                }else
                {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Warning, 'No record found'));
                    
                }
            }
            else
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Fatal, 'Please Select A value'));
            }
        
    }

}