src/objects/Users__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Users</label>
    <nameField>
        <label>Users Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/loginController.cls
public class loginController {
    public string userID{get;set;}
    public string password{get;set;}
    public string retUrl;
    
     public PageReference login() {
     
     list<Users__c> lstUser=new list<Users__c>();
     lstUser=[select name,password__c  from Users__c where name=:userID ];
     if(lstUser.size()==0)
     {
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Invalid Password or user Id'));
         return null;
     }
     else
     {    
        PageReference pageRef = new PageReference('/apex/PostLogin');
        
                 
        return pageRef ;
     }
    }
    
    
}